version: '2'
services:
  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - ./:/app
    links:
      - mongo
    environment:
      - ENVIRONMENT=production
  mongo:
    image: mongo:latest
